### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by JIAFALSEDREAM** [hsyhhssyy/amiyabot-hsyhhssyy-wordcloud#1]
如图
![微信图片_20230428193618](https://user-images.githubusercontent.com/121747365/235137492-fc14c7c9-35a2-4473-a34c-f8a1d02781e5.jpg)

**Comment by hsyhhssyy** [comment]
你的resource/msyh.ttf文件对吗?能打开吗?
如果不行,你找一个别的字体,替换掉这个文件试试。
这是wordcloud库报的错，他似乎不认这个字体。

**Comment by JIAFALSEDREAM** [comment]
还是报错
![1682856803525](https://user-images.githubusercontent.com/121747365/235352336-a89eec95-5400-4f75-a26e-86c88f70f8d2.png)

**Comment by Mak1seKur1su** [comment]
我今天同样出现了此问题，并且尝试替换了两个字体文件，依旧报错

**Comment by hsyhhssyy** [comment]
> 

@Mak1seKur1su  @JIAFALSEDREAM 

以前是好的,今天突然就不行了是么

你们是升级过wordcloud库吗？ 能看一下wordcloud库的版本吗？

因为我刚刚还试了一下没什么问题,我怀疑是库升级了？

执行下面的命令试着查询一下你当前的库版本

python -c "import wordcloud; print(wordcloud.__version__)"

把插件删了重装试一下呢？

**Comment by hsyhhssyy** [comment]
![image](https://user-images.githubusercontent.com/5977110/235360442-2d8c3cbd-5ec7-40d3-99da-61494b8b3d20.png)

我看到pypi上，wordcloud库4月28日刚刚发布了1.9的新版本，我猜，这个版本有bug

**Comment by Mak1seKur1su** [comment]
> > 
> 
> @Mak1seKur1su @JIAFALSEDREAM
> 
> 以前是好的,今天突然就不行了是么
> 
> 你们是升级过wordcloud库吗？ 能看一下wordcloud库的版本吗？
> 
> 因为我刚刚还试了一下没什么问题,我怀疑是库升级了？
> 
> 执行下面的命令试着查询一下你当前的库版本
> 
> python -c "import wordcloud; print(wordcloud.**version**)"
> 
> 把插件删了重装试一下呢？

我是今天刚安装的，wordcloud版本是1.9.1.1

**Comment by Mak1seKur1su** [comment]
wordcloud库已退回1.8.2.2版本，报错消失，已经可以正常使用了

**Comment by JIAFALSEDREAM** [comment]
同今天安装
回退1.8.2.2后恢复正常使用

**Comment by JIAFALSEDREAM** [comment]
所以这个issue可以关了？

**Comment by hsyhhssyy** [comment]
我改一下readme，然后再关
